apiVersion: v1
kind: Service
metadata:
  name: apache-loadbalancer-service
spec:
  selector:
    app: custom-apache1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer